version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    env_file:
      - .env
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./postgres/Iris.csv:/docker-entrypoint-initdb.d/Iris.csv
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  mongodb:
    image: mongo:7
    container_name: mongodb_db
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DB}
    env_file:
      - .env
    ports:
      - "${MONGO_PORT}:27017"
    volumes:
      - mongodb_data:/data/db
      - ./mongo:/docker-entrypoint-initdb.d
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mongosh", "--quiet", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

  mongo_express:
    image: mongo-express:latest
    container_name: mongo_express
    restart: always
    env_file:
      - .env
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGO_ROOT_USERNAME}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_ROOT_PASSWORD}
      - ME_CONFIG_MONGODB_URL=mongodb://${MONGO_ROOT_USERNAME}:${MONGO_ROOT_PASSWORD}@mongodb_db:27017/${MONGO_DB}?authSource=admin
      - ME_CONFIG_BASICAUTH=true
      - ME_CONFIG_BASICAUTH_USERNAME=${MONGO_ROOT_USERNAME}
      - ME_CONFIG_BASICAUTH_PASSWORD=${MONGO_ROOT_PASSWORD}
    ports:
      - "${MONGO_EXPRESS_PORT:-8081}:8081"
    networks:
      - app-network
    depends_on:
      mongodb:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8081"]
      interval: 30s
      timeout: 10s
      retries: 3

  ollama:
    image: ollama/ollama:latest
    container_name: ollama-server
    restart: unless-stopped
    environment:
      - OLLAMA_HOST=0.0.0.0:11434
      - OLLAMA_ORIGINS=${OLLAMA_ORIGINS}
      - OLLAMA_KEEP_ALIVE=${OLLAMA_KEEP_ALIVE}
      - OLLAMA_DEBUG=${OLLAMA_DEBUG}
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    ports:
      - "${OLLAMA_PORT}:11434"
    volumes:
      - ollama_data:/root/.ollama
      - ./ollama/entrypoint.sh:/entrypoint.sh:ro
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "ollama", "list"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    entrypoint: ["sh", "/entrypoint.sh"]

  miniconda:
    build:
      context: ./python
      dockerfile: Dockerfile
    container_name: miniconda_app
    restart: always
    env_file:
      - .env
    volumes:
      - ./python/src:/app/src
    networks:
      - app-network
    depends_on:
      ollama:
        condition: service_healthy
      postgres:
        condition: service_healthy
      mongodb:
        condition: service_healthy
      mc-client-init:
        condition: service_completed_successfully
    command: ["bash", "/app/entrypoint.sh"]

  streamlit:
    build:
      context: ./streamlit
      dockerfile: Dockerfile
    container_name: streamlit_app
    restart: always
    env_file:
      - .env
    ports:
      - "${STREAMLIT_PORT}:8501"
    volumes:
      - ./streamlit/src:/app/src
    networks:
      - app-network
    depends_on:
      ollama:
        condition: service_healthy
      postgres:
        condition: service_healthy
      mongodb:
        condition: service_healthy
      mc-client-init:
        condition: service_healthy
    command: ["bash", "/app/entrypoint.sh"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8501/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3

  minio:
    image: minio/minio:latest
    container_name: minio_server
    restart: always
    ports:
      - "${MINIO_PORT}:9000"     # accès API S3
      - "9001:9001"              # console web MinIO
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    command: server /data --console-address ":9001"
    volumes:
      - ./minio/data:/data       # persister buckets et objets
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 10s
      timeout: 5s
      retries: 5

  # --- service d'initialisation (crée bucket + copie images) ---
  mc-client-init:
    image: minio/mc:latest
    container_name: mc_client_init
    restart: "no"                # ne pas relancer une fois terminé
    depends_on:
      minio:
        condition: service_healthy
    volumes:
      - ./minio/images:/images:ro    # dossier local d'images
      - ./minio/init/init.sh:/init.sh:ro
    environment:
      # alias 'local' pointant vers MinIO (auth + host)
      MC_HOST_local: "http://${MINIO_ROOT_USER}:${MINIO_ROOT_PASSWORD}@minio:9000"
      BUCKET_NAME: "${MINIO_BUCKET_NAME:-my-bucket}"
    entrypoint: ["/bin/sh", "/init.sh"]
    networks:
      - app-network

volumes:
  postgres_data:
  mongodb_data:
  ollama_data:

networks:
  app-network:
    driver: bridge
